name: Vcpkg C++ CI

on: [push]

jobs:
  build:
    name: Build C++ Project
    runs-on: windows-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          runVcpkgInstall: true

      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v1.1

      - name: Build C++ Code
        run: |
          cl.exe /EHsc /std:c++17 main.cpp /I"${{ github.workspace }}/vcpkg/installed/x64-windows/include" /link /LIBPATH:"${{ github.workspace }}/vcpkg/installed/x64-windows/lib"
        shell: cmd
